### ISSUE TITLE
Cannot install dvbtee

### ISSUE THREAD

**Issue by buzzdev** [mkrufky/node-dvbtee#19]
```
$ node -v
v8.2.0
```

```
$ npm -v
5.6.0
```

```
$ npm install dvbtee

dvbtee@0.3.6 install /home/minarima/Documents/dvbteenode/node_modules/dvbtee
node-gyp rebuild -j 8

/usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin/node-gyp: 5: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin/node-gyp: /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js: Permission denied
npm WARN dvbteenode@1.0.0 No description
npm WARN dvbteenode@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 126
npm ERR! dvbtee@0.3.6 install: node-gyp rebuild -j 8
npm ERR! Exit status 126
npm ERR! 
npm ERR! Failed at the dvbtee@0.3.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

Debug log:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'install', 'dvbtee' ]
2 info using npm@5.6.0
3 info using node@v8.2.0
4 verbose npm-session 7430bba85a75e7cb
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://registry.npmjs.org/dvbtee 118ms (from cache)
8 silly pacote tag manifest for dvbtee@latest fetched in 134ms
9 silly install loadIdealTree
10 silly install cloneCurrentTreeToIdealTree
11 silly install loadShrinkwrap
12 silly install loadAllDepsIntoIdealTree
13 silly resolveWithNewModule dvbtee@0.3.6 checking installable status
14 silly currentTree dvbteenode@1.0.0
14 silly currentTree ├── bindings@1.3.0
14 silly currentTree └── nan@2.8.0
15 silly idealTree dvbteenode@1.0.0
15 silly idealTree ├── bindings@1.3.0
15 silly idealTree ├── dvbtee@0.3.6
15 silly idealTree └── nan@2.8.0
16 silly install generateActionsToTake
17 silly diffTrees action count 1
18 silly diffTrees add dvbtee@0.3.6
19 silly decomposeActions action count 8
20 silly decomposeActions fetch dvbtee@0.3.6
21 silly decomposeActions extract dvbtee@0.3.6
22 silly decomposeActions preinstall dvbtee@0.3.6
23 silly decomposeActions build dvbtee@0.3.6
24 silly decomposeActions install dvbtee@0.3.6
25 silly decomposeActions postinstall dvbtee@0.3.6
26 silly decomposeActions finalize dvbtee@0.3.6
27 silly decomposeActions refresh-package-json dvbtee@0.3.6
28 silly install executeActions
29 silly doSerial global-install 8
30 verbose correctMkdir /home/minarima/.npm/_locks correctMkdir not in flight; initializing
31 verbose lock using /home/minarima/.npm/_locks/staging-75c7cb12666ac3df.lock for /home/minarima/Documents/dvbteenode/node_modules/.staging
32 silly doParallel extract 8
33 silly extract dvbtee@0.3.6
34 silly pacote trying dvbtee@https://registry.npmjs.org/dvbtee/-/dvbtee-0.3.6.tgz by hash: sha1-U2l46q1kEz4L4s2PkyoCZxeVgQw=
35 silly pacote dvbtee@https://registry.npmjs.org/dvbtee/-/dvbtee-0.3.6.tgz extracted to /home/minarima/Documents/dvbteenode/node_modules/.staging/dvbtee-893d6024 by content address 113ms
36 silly doReverseSerial unbuild 8
37 silly doSerial remove 8
38 silly doSerial move 8
39 silly doSerial finalize 8
40 silly finalize /home/minarima/Documents/dvbteenode/node_modules/dvbtee
41 silly doParallel refresh-package-json 8
42 silly refresh-package-json /home/minarima/Documents/dvbteenode/node_modules/dvbtee
43 silly doParallel preinstall 8
44 silly preinstall dvbtee@0.3.6
45 info lifecycle dvbtee@0.3.6~preinstall: dvbtee@0.3.6
46 silly doSerial build 8
47 silly build dvbtee@0.3.6
48 info linkStuff dvbtee@0.3.6
49 silly linkStuff dvbtee@0.3.6 has /home/minarima/Documents/dvbteenode/node_modules as its parent node_modules
50 verbose linkBins dvbtee@0.3.6
51 verbose linkMans dvbtee@0.3.6
52 silly doSerial global-link 8
53 silly doParallel update-linked 8
54 silly doSerial install 8
55 silly install dvbtee@0.3.6
56 info lifecycle dvbtee@0.3.6~install: dvbtee@0.3.6
57 verbose lifecycle dvbtee@0.3.6~install: unsafe-perm in lifecycle true
58 verbose lifecycle dvbtee@0.3.6~install: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/minarima/Documents/dvbteenode/node_modules/dvbtee/node_modules/.bin:/home/minarima/Documents/dvbteenode/node_modules/.bin:/home/minarima/.cargo/bin:/home/minarima/bin:/home/minarima/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
59 verbose lifecycle dvbtee@0.3.6~install: CWD: /home/minarima/Documents/dvbteenode/node_modules/dvbtee
60 silly lifecycle dvbtee@0.3.6~install: Args: [ '-c', 'node-gyp rebuild -j 8' ]
61 silly lifecycle dvbtee@0.3.6~install: Returned: code: 126  signal: null
62 info lifecycle dvbtee@0.3.6~install: Failed to exec install script
63 verbose unlock done using /home/minarima/.npm/_locks/staging-75c7cb12666ac3df.lock for /home/minarima/Documents/dvbteenode/node_modules/.staging
64 silly saveTree dvbteenode@1.0.0
64 silly saveTree ├── bindings@1.3.0
64 silly saveTree ├─┬ dvbtee@0.3.6
64 silly saveTree │ └── nan@2.8.0
64 silly saveTree └── nan@2.8.0
65 warn dvbteenode@1.0.0 No description
66 warn dvbteenode@1.0.0 No repository field.
67 verbose stack Error: dvbtee@0.3.6 install: `node-gyp rebuild -j 8`
67 verbose stack Exit status 126
67 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
67 verbose stack     at emitTwo (events.js:125:13)
67 verbose stack     at EventEmitter.emit (events.js:213:7)
67 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
67 verbose stack     at emitTwo (events.js:125:13)
67 verbose stack     at ChildProcess.emit (events.js:213:7)
67 verbose stack     at maybeClose (internal/child_process.js:921:16)
67 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
68 verbose pkgid dvbtee@0.3.6
69 verbose cwd /home/minarima/Documents/dvbteenode
70 verbose Linux 4.10.0-42-generic
71 verbose argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "dvbtee"
72 verbose node v8.2.0
73 verbose npm  v5.6.0
74 error code ELIFECYCLE
75 error errno 126
76 error dvbtee@0.3.6 install: `node-gyp rebuild -j 8`
76 error Exit status 126
77 error Failed at the dvbtee@0.3.6 install script.
77 error This is probably not a problem with npm. There is likely additional logging output above.
78 verbose exit [ 126, true ]
```

**Comment by buzzdev** [comment]
And so i've just downgraded npm to v5.3.0 and install worked.
```
npm -v
5.3.0
```
```
node -v
v8.2.0
```

**Comment by mkrufky** [comment]
closing this, as it seems to be environment specific.  If you are still encountering this problem (or similar) then please feel free to reopen.
